//NON-PRIMITIVE

 //1.OBJECTS
/*
 let username={
     firstname:"vivek",
     isLoggedin:true,
     "sports":"cricket"// for acces this we use different methods
 };

 username.firstname="Mr.R";//update value

 username.lastname="verma";//add new key and value

 console.log(username);//
console.log(username.lastname);//verma
  console.log(username['sports']);// use this for acces ="sports":"cricket"
 console.log(typeof username);//object
 */

 //2.DATE

 let today=new Date()
 console.log(today);//2025-09-02T11:36:15.683Z

 // use  and practice all  properties

 console.log(today.getDate());//2


 //3.Arrays

 let name=["a","b","c",true,45]
 console.log(name);//[ 'a', 'b', 'c', true, 45 ]

 let anotherUser=["hitesh","luv",true]
 console.log(anotherUser[0]);//hitesh
 console.log(anotherUser[1]);//luv 
 console.log(anotherUser[2]);//TRUE

 let isValue =true//true always a =1
 console.log(isValue+1)//2


 
 
 
 
 
 